### PR TITLE
Fix serializers and improve their typings

### PR DESCRIPTION
**Pull request by EdJoPaTo**
Before this fix no serializer was specified when the constructor options
set one. The if would be false and nothing would set the serializer.

also fix typo in default folderPath

also used deno fmt/lint for exactly this file to ensure some formatting

This might be considered a breaking change but as it fixes non working
code of a new feature I would see this as a bugfix rather than a
breaking major.

### CODE REVIEW

**Comment by Satont** [comment]
> Before this fix no serializer was specified when the constructor options
set one. The if would be false and nothing would set the serializer.

`??` not fixing that issue, because this operator check for `null | undefined`.

**Comment by EdJoPaTo** [comment]
There are two possible cases (assuming typescript types are used):
- `opt.serializer` is set and a valid function
- `opt.serializer` is not set (undefined)

`undefined ?? default` → `default`
`definedAndValid ?? default` → `definedAndValid`

Am I overlooking something?

The suggested check for `typeof … === function` would require misuse of TypeScript or JavaScript with wrong input. Whatever happens there will fail later at `this.serializer` like it does currently when a serializer is set via arguments.

Personally I try to ensure correct TypeScript types and ignore misusage / JavaScript usage as using TypeScript can prevent these kinds of errors for free at compile time.

**Comment by Satont** [comment]
> Am I overlooking something?

Yes with typecsript also my option will work as yours. But your is shorten, so i see no difference.

> Whatever happens there will fail later at this.serializer like it does currently when a serializer is set via arguments.

Shouldn't we throw error to user on the startup?

**Comment by EdJoPaTo** [comment]
> > Am I overlooking something?
> 
> Yes with typecsript also my option will work as yours. But your is shorten, so i see no difference.

The current code is only checking `if (!opts.serializer)` but the `if (opts.serializer)` case is never handled. Therefore `this.serializer` is not set when `opts.serializer` is set which will fail as soon as its used.
As the typings currently allow for `function | undefined` typescript doesn't even notice this bug currently. The only place in the current code which highlights there is something wrong is the `!` when `this.serializer` is used. The `!` operator in TypeScript is is basically a warning sign that there might be something wrong which actually is the case here.

> > Whatever happens there will fail later at this.serializer like it does currently when a serializer is set via arguments.
> 
> Shouldn't we throw error to user on the startup?
> 
> we can check
> 
> ```ts
> if (typeof opts.serializer !== 'function' || typeof opts.desirializer !== 'function') {
>    throw new Error("...")
> } else {
>  this.serializer = opts.serializer ?? default
>  this.deserializer = opts.deserializer ?? default
> }
> ```

I can understand why something like this is helpful for JavaScript users. Personal opinion is to ensure correct typings and let TypeScript check for errors like this which is not only a check I don't have to write myself but also at compile time rather than at runtime. I think this should be thought about separately from this bug fix.

**Comment by Satont** [comment]
Make sense. LGTM

**Pull request merged**
